# -*- coding: utf-8 -*-
"""Funding_Factors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TfxVyvBJHNB_MLSMNsD3b81k9YmbcgaP
"""

# Commented out IPython magic to ensure Python compatibility.
### Load relevant packages
import pandas                  as pd
import numpy                   as np
import matplotlib.pyplot       as plt
import seaborn                 as sns
import statsmodels.formula.api as sm
import os

# %matplotlib inline
plt.style.use('ggplot')

from google.colab import drive
drive.mount('/content/drive')
!ls
df = pd.read_csv('/content/drive/Shared drives/Data Science for All - Womens Summit/Data/US Crunchbase Companies.csv')
df.head()

df.columns.values

df_women = df[df['Diversity Spotlight (US Only)'].astype(str).str.contains("Women")]
len(df)
# total number of women founded businesses in our data
# len(df_women)

# percentage of women founded businesses in our data
# len(df_women)/len(df)

# total funding amount for women founded businesses in our data
women_total_funding = df_women['Total Funding Amount Currency (in USD)'].astype('float').sum()
# women_total_funding

# number of women founded businesses that raised 0 funding
women_funding_zero = df_women['Total Funding Amount Currency (in USD)'].isnull().sum()
women_funding_zero

# number of women founded businesses with non-zero founding amount
women_funding_non_zero = df_women['Total Funding Amount Currency (in USD)'].dropna()
len(women_funding_non_zero)

# number of women founded businesses that receive some funds but less than 200k
type(women_funding_non_zero.astype('float')  < 200000.0)
women_funding_nonzero_200K = women_funding_non_zero.where(women_funding_non_zero.astype('float')  >= 200000.0).isnull().sum()
women_funding_nonzero_200K

# total number of women founded businesses that either receive no funds or receive funds less than 200K
women_funding_200K = women_funding_zero + women_funding_nonzero_200K
women_funding_200K

# percentage of women founded businesses that either receive no funds or receive funds less than 200K
percent_women_funding_200K = women_funding_200K / len(df_women)
percent_women_funding_200K

women_revenue_non_zero = df_women['Estimated Revenue Range'].dropna()
# number of women founded businesses that have less than 1M estimated revenue
women_revenue_less_1M = women_revenue_non_zero.where(women_revenue_non_zero != 'Less than $1M').isnull().sum()
women_revenue_less_1M

# percentage of women founded businesses that have less than 1M estimated revenue
women_revenue_less_1M / len(women_revenue_non_zero)

print("Total number of women founded/led businesses:\n", len(df_women))
print("Percentage of women founded/led businesses:\n", len(df_women)/len(df))
print("Number of women founded/led businesses that raised 0 funding:\n", women_funding_zero)
print("Number of women founded/led businesses that receive some funds but less than 200k:\n", women_funding_nonzero_200K)
print("Total number of women founded/led businesses that either receive no funds or receive funds less than 200K:\n", women_funding_200K)
print("Percentage of women founded/led businesses that either receive no funds or receive funds less than 200K:\n", percent_women_funding_200K)
print("Number of women founded/led businesses that have non-empty estimated revenue:\n", len(women_revenue_non_zero))
print("Number of women founded/led businesses that have less than 1M estimated revenue:\n", women_revenue_less_1M)
print("Percentage of women founded/led businesses that have less than 1M estimated revenue:\n", women_revenue_less_1M / len(women_revenue_non_zero))

# plot for estimated revenue range of women founded/led businesses
plot = df_women['Estimated Revenue Range'].value_counts(normalize=True).plot.bar().set_title('Percentage of Women Founded/Led Businesses regarding Estimated Revenue Range')